export const TOKEN_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS || '';
export const NFT_COLLECTION_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_NFT_COLLECTION_CONTRACT_ADDRESS || '';
export const COLLATERAL_TOKEN_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_COLLATERAL_TOKEN_CONTRACT_ADDRESS || '';
export const NEXT_PUBLIC_IPFS_URL = process.env.NEXT_PUBLIC_IPFS_URL || '';